# Config file of BossTrollRework v0.1

Permissions:
  UseTrollCommand: 'bosstroll.command'

Tools:
  FireBallExplosionRange: 3
  ExplosionBowRange: 3

RandomChatTroll:
  Messages:
    - 'I am dumb'
    - 'Please OP me!!!11!'
    - 'This server is bad!'

LagTroll:
  Delay: 3

FakeBan:
  Message:
    - '&8&m------------------------'
    - '&7'
    - '&4&lYOURNETWORK.COM'
    - '&cYou have been banned from the server.'
    - ''
    - '&cReason&8: &7Insulting other players'
    - '&cDuration&8: &730 days'
    - '&7'
    - '&7If you think this is an error, visit our'
    - '&7forums page &cforum.yournetwork.com &7to repeal.'
    - '&7'
    - '&8&m------------------------'

MathTroll:

  Time: 5

  # The math exercises a player can get
  # Please use the following format to add new ones:
  # 'your exercise==solution'
  # Your solution must be an integer!
  # -> Allowed: 1, 2, 4355, 23, -23445
  # -> Denied: 99.99, abcde, 1/4
  Exercises:
    - '1 + 1==2'
    - '6 + 3==9'
    - '6 / 2==3'
    - 'The double of 10==20'